### ISSUE TITLE
0.0.0.0 -> 0.0.0.1 violated PVP version contract.

### ISSUE THREAD

**Issue by phadej** [parsonsmatt/plucky#3]
You **added** new exports to the `Data.Either.Plucky` interface.

> *Non-breaking change*. Otherwise, if only new bindings, types, classes, non-orphan instances or modules (but see below) were added to the interface, then A.B MAY remain the same but the new C **MUST** be greater than the old C. Note that modifying imports or depending on a newer version of another package may cause extra non-orphan instances to be exported and thus force a minor version change.

In fact, **you removed an entity**, namely `promote` which would required a major bump.

I recommend blacklisting, i.e. making revision on `0.0.0.0` or `0.0.0.1` with `build-depends: base <0` (unsatisfiable constraint), to pretend that version never existed.

Here are a few things to keep in mind when uploading to Hackage
that help keep the ecosystem working reliably for everyone:

1. Hackage is intended to be a permanent record.  Therefore uploads
cannot be changed or removed.
2. Only upload things that work, are useful to other people, and that
you intend to maintain.
3. Package candidates CAN be changed, so use them to test things out
and get everything right before you publish permanently to the main
index.

**Comment by parsonsmatt** [comment]
Thanks for the notice! The library is currently in 'alpha' and I don't intend on following PVP until I release a `0.1.0.0` version, which will be more complete. If there's a flag I can set that'll make that more obvious, I'd be happy to set that.

I did not use a Hackage candidate as I wanted documentation rendered/generated.

**Comment by phadej** [comment]
I assume that intention is to have the package on Stackage eventually, so I ask you: Don't upload any new versions on Hackage, if you aren't putting them on Stackage.

You can generate documentation locally, and upload it e.g. to GitHub pages.

There are no really visible flag. All packages uploaded to Hackage are meant to be useful to others. This package and its current state fails to achieve that (i.e. it cannot be depended upon).

EDIT: there's `x-curation: uncurated-no-trustee-contact` field described on https://hackage.haskell.org/upload.

**Comment by parsonsmatt** [comment]
Thanks for the edits! I'll blacklist 0.0.0.0 and abstain from releasing until it's in a PVP-ready state.

**Comment by phadej** [comment]
@parsonsmatt thank you

**Comment by cartazio** [comment]
More concretely, please adhere to pvp for hackage uploads.

**Comment by cartazio** [comment]
Derp, stale tab. Ignore me :)
